// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: qosm.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_HIGH        Priority = 10
	Priority_PRIORITY_LOW         Priority = 20
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0:  "PRIORITY_UNSPECIFIED",
		10: "PRIORITY_HIGH",
		20: "PRIORITY_LOW",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_HIGH":        10,
		"PRIORITY_LOW":         20,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_qosm_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_qosm_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Service struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Port        int32                  `protobuf:"varint,1,opt,name=port"`
	xxx_hidden_Protocol    int32                  `protobuf:"varint,2,opt,name=protocol"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_qosm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Service) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *Service) GetProtocol() int32 {
	if x != nil {
		return x.xxx_hidden_Protocol
	}
	return 0
}

func (x *Service) SetPort(v int32) {
	x.xxx_hidden_Port = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Service) SetProtocol(v int32) {
	x.xxx_hidden_Protocol = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Service) HasPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Service) HasProtocol() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Service) ClearPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Port = 0
}

func (x *Service) ClearProtocol() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Protocol = 0
}

type Service_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Port     *int32
	Protocol *int32
}

func (b0 Service_builder) Build() *Service {
	m0 := &Service{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Port != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Port = *b.Port
	}
	if b.Protocol != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Protocol = *b.Protocol
	}
	return m0
}

type Interface struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Ifindex     int32                  `protobuf:"varint,2,opt,name=ifindex"`
	xxx_hidden_Rate        uint32                 `protobuf:"varint,3,opt,name=rate"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_qosm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Interface) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Interface) GetIfindex() int32 {
	if x != nil {
		return x.xxx_hidden_Ifindex
	}
	return 0
}

func (x *Interface) GetRate() uint32 {
	if x != nil {
		return x.xxx_hidden_Rate
	}
	return 0
}

func (x *Interface) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Interface) SetIfindex(v int32) {
	x.xxx_hidden_Ifindex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Interface) SetRate(v uint32) {
	x.xxx_hidden_Rate = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Interface) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Interface) HasIfindex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Interface) HasRate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Interface) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Interface) ClearIfindex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ifindex = 0
}

func (x *Interface) ClearRate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Rate = 0
}

type Interface_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    *string
	Ifindex *int32
	Rate    *uint32
}

func (b0 Interface_builder) Build() *Interface {
	m0 := &Interface{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Ifindex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Ifindex = *b.Ifindex
	}
	if b.Rate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Rate = *b.Rate
	}
	return m0
}

type IPPrefix struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ip          []byte                 `protobuf:"bytes,1,opt,name=ip"`
	xxx_hidden_PrefixLen   int32                  `protobuf:"varint,2,opt,name=prefix_len,json=prefixLen"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IPPrefix) Reset() {
	*x = IPPrefix{}
	mi := &file_qosm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPPrefix) ProtoMessage() {}

func (x *IPPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IPPrefix) GetIp() []byte {
	if x != nil {
		return x.xxx_hidden_Ip
	}
	return nil
}

func (x *IPPrefix) GetPrefixLen() int32 {
	if x != nil {
		return x.xxx_hidden_PrefixLen
	}
	return 0
}

func (x *IPPrefix) SetIp(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Ip = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *IPPrefix) SetPrefixLen(v int32) {
	x.xxx_hidden_PrefixLen = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *IPPrefix) HasIp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IPPrefix) HasPrefixLen() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IPPrefix) ClearIp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ip = nil
}

func (x *IPPrefix) ClearPrefixLen() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PrefixLen = 0
}

type IPPrefix_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ip        []byte
	PrefixLen *int32
}

func (b0 IPPrefix_builder) Build() *IPPrefix {
	m0 := &IPPrefix{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ip != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Ip = b.Ip
	}
	if b.PrefixLen != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_PrefixLen = *b.PrefixLen
	}
	return m0
}

type Request struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Command isRequest_Command      `protobuf_oneof:"command"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_qosm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Request) GetAddHosts() *AddHosts {
	if x != nil {
		if x, ok := x.xxx_hidden_Command.(*request_AddHosts); ok {
			return x.AddHosts
		}
	}
	return nil
}

func (x *Request) GetDeleteHosts() *DeleteHosts {
	if x != nil {
		if x, ok := x.xxx_hidden_Command.(*request_DeleteHosts); ok {
			return x.DeleteHosts
		}
	}
	return nil
}

func (x *Request) GetAddServices() *AddServices {
	if x != nil {
		if x, ok := x.xxx_hidden_Command.(*request_AddServices); ok {
			return x.AddServices
		}
	}
	return nil
}

func (x *Request) GetDeleteServices() *DeleteServices {
	if x != nil {
		if x, ok := x.xxx_hidden_Command.(*request_DeleteServices); ok {
			return x.DeleteServices
		}
	}
	return nil
}

func (x *Request) GetEnableIfaces() *EnableIfaces {
	if x != nil {
		if x, ok := x.xxx_hidden_Command.(*request_EnableIfaces); ok {
			return x.EnableIfaces
		}
	}
	return nil
}

func (x *Request) GetDisableIfaces() *DisableIfaces {
	if x != nil {
		if x, ok := x.xxx_hidden_Command.(*request_DisableIfaces); ok {
			return x.DisableIfaces
		}
	}
	return nil
}

func (x *Request) GetFlushRules() *FlushRules {
	if x != nil {
		if x, ok := x.xxx_hidden_Command.(*request_FlushRules); ok {
			return x.FlushRules
		}
	}
	return nil
}

func (x *Request) SetAddHosts(v *AddHosts) {
	if v == nil {
		x.xxx_hidden_Command = nil
		return
	}
	x.xxx_hidden_Command = &request_AddHosts{v}
}

func (x *Request) SetDeleteHosts(v *DeleteHosts) {
	if v == nil {
		x.xxx_hidden_Command = nil
		return
	}
	x.xxx_hidden_Command = &request_DeleteHosts{v}
}

func (x *Request) SetAddServices(v *AddServices) {
	if v == nil {
		x.xxx_hidden_Command = nil
		return
	}
	x.xxx_hidden_Command = &request_AddServices{v}
}

func (x *Request) SetDeleteServices(v *DeleteServices) {
	if v == nil {
		x.xxx_hidden_Command = nil
		return
	}
	x.xxx_hidden_Command = &request_DeleteServices{v}
}

func (x *Request) SetEnableIfaces(v *EnableIfaces) {
	if v == nil {
		x.xxx_hidden_Command = nil
		return
	}
	x.xxx_hidden_Command = &request_EnableIfaces{v}
}

func (x *Request) SetDisableIfaces(v *DisableIfaces) {
	if v == nil {
		x.xxx_hidden_Command = nil
		return
	}
	x.xxx_hidden_Command = &request_DisableIfaces{v}
}

func (x *Request) SetFlushRules(v *FlushRules) {
	if v == nil {
		x.xxx_hidden_Command = nil
		return
	}
	x.xxx_hidden_Command = &request_FlushRules{v}
}

func (x *Request) HasCommand() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Command != nil
}

func (x *Request) HasAddHosts() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Command.(*request_AddHosts)
	return ok
}

func (x *Request) HasDeleteHosts() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Command.(*request_DeleteHosts)
	return ok
}

func (x *Request) HasAddServices() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Command.(*request_AddServices)
	return ok
}

func (x *Request) HasDeleteServices() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Command.(*request_DeleteServices)
	return ok
}

func (x *Request) HasEnableIfaces() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Command.(*request_EnableIfaces)
	return ok
}

func (x *Request) HasDisableIfaces() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Command.(*request_DisableIfaces)
	return ok
}

func (x *Request) HasFlushRules() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Command.(*request_FlushRules)
	return ok
}

func (x *Request) ClearCommand() {
	x.xxx_hidden_Command = nil
}

func (x *Request) ClearAddHosts() {
	if _, ok := x.xxx_hidden_Command.(*request_AddHosts); ok {
		x.xxx_hidden_Command = nil
	}
}

func (x *Request) ClearDeleteHosts() {
	if _, ok := x.xxx_hidden_Command.(*request_DeleteHosts); ok {
		x.xxx_hidden_Command = nil
	}
}

func (x *Request) ClearAddServices() {
	if _, ok := x.xxx_hidden_Command.(*request_AddServices); ok {
		x.xxx_hidden_Command = nil
	}
}

func (x *Request) ClearDeleteServices() {
	if _, ok := x.xxx_hidden_Command.(*request_DeleteServices); ok {
		x.xxx_hidden_Command = nil
	}
}

func (x *Request) ClearEnableIfaces() {
	if _, ok := x.xxx_hidden_Command.(*request_EnableIfaces); ok {
		x.xxx_hidden_Command = nil
	}
}

func (x *Request) ClearDisableIfaces() {
	if _, ok := x.xxx_hidden_Command.(*request_DisableIfaces); ok {
		x.xxx_hidden_Command = nil
	}
}

func (x *Request) ClearFlushRules() {
	if _, ok := x.xxx_hidden_Command.(*request_FlushRules); ok {
		x.xxx_hidden_Command = nil
	}
}

const Request_Command_not_set_case case_Request_Command = 0
const Request_AddHosts_case case_Request_Command = 1
const Request_DeleteHosts_case case_Request_Command = 2
const Request_AddServices_case case_Request_Command = 3
const Request_DeleteServices_case case_Request_Command = 4
const Request_EnableIfaces_case case_Request_Command = 5
const Request_DisableIfaces_case case_Request_Command = 6
const Request_FlushRules_case case_Request_Command = 7

func (x *Request) WhichCommand() case_Request_Command {
	if x == nil {
		return Request_Command_not_set_case
	}
	switch x.xxx_hidden_Command.(type) {
	case *request_AddHosts:
		return Request_AddHosts_case
	case *request_DeleteHosts:
		return Request_DeleteHosts_case
	case *request_AddServices:
		return Request_AddServices_case
	case *request_DeleteServices:
		return Request_DeleteServices_case
	case *request_EnableIfaces:
		return Request_EnableIfaces_case
	case *request_DisableIfaces:
		return Request_DisableIfaces_case
	case *request_FlushRules:
		return Request_FlushRules_case
	default:
		return Request_Command_not_set_case
	}
}

type Request_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Command:
	AddHosts       *AddHosts
	DeleteHosts    *DeleteHosts
	AddServices    *AddServices
	DeleteServices *DeleteServices
	EnableIfaces   *EnableIfaces
	DisableIfaces  *DisableIfaces
	FlushRules     *FlushRules
	// -- end of xxx_hidden_Command
}

func (b0 Request_builder) Build() *Request {
	m0 := &Request{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AddHosts != nil {
		x.xxx_hidden_Command = &request_AddHosts{b.AddHosts}
	}
	if b.DeleteHosts != nil {
		x.xxx_hidden_Command = &request_DeleteHosts{b.DeleteHosts}
	}
	if b.AddServices != nil {
		x.xxx_hidden_Command = &request_AddServices{b.AddServices}
	}
	if b.DeleteServices != nil {
		x.xxx_hidden_Command = &request_DeleteServices{b.DeleteServices}
	}
	if b.EnableIfaces != nil {
		x.xxx_hidden_Command = &request_EnableIfaces{b.EnableIfaces}
	}
	if b.DisableIfaces != nil {
		x.xxx_hidden_Command = &request_DisableIfaces{b.DisableIfaces}
	}
	if b.FlushRules != nil {
		x.xxx_hidden_Command = &request_FlushRules{b.FlushRules}
	}
	return m0
}

type case_Request_Command protoreflect.FieldNumber

func (x case_Request_Command) String() string {
	md := file_qosm_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRequest_Command interface {
	isRequest_Command()
}

type request_AddHosts struct {
	AddHosts *AddHosts `protobuf:"bytes,1,opt,name=add_hosts,json=addHosts,oneof"`
}

type request_DeleteHosts struct {
	DeleteHosts *DeleteHosts `protobuf:"bytes,2,opt,name=delete_hosts,json=deleteHosts,oneof"`
}

type request_AddServices struct {
	AddServices *AddServices `protobuf:"bytes,3,opt,name=add_services,json=addServices,oneof"`
}

type request_DeleteServices struct {
	DeleteServices *DeleteServices `protobuf:"bytes,4,opt,name=delete_services,json=deleteServices,oneof"`
}

type request_EnableIfaces struct {
	EnableIfaces *EnableIfaces `protobuf:"bytes,5,opt,name=enable_ifaces,json=enableIfaces,oneof"`
}

type request_DisableIfaces struct {
	DisableIfaces *DisableIfaces `protobuf:"bytes,6,opt,name=disable_ifaces,json=disableIfaces,oneof"`
}

type request_FlushRules struct {
	FlushRules *FlushRules `protobuf:"bytes,7,opt,name=flush_rules,json=flushRules,oneof"`
}

func (*request_AddHosts) isRequest_Command() {}

func (*request_DeleteHosts) isRequest_Command() {}

func (*request_AddServices) isRequest_Command() {}

func (*request_DeleteServices) isRequest_Command() {}

func (*request_EnableIfaces) isRequest_Command() {}

func (*request_DisableIfaces) isRequest_Command() {}

func (*request_FlushRules) isRequest_Command() {}

type Response struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Response isResponse_Response    `protobuf_oneof:"response"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_qosm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Response) GetSuccessOp() *Success {
	if x != nil {
		if x, ok := x.xxx_hidden_Response.(*response_SuccessOp); ok {
			return x.SuccessOp
		}
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		if x, ok := x.xxx_hidden_Response.(*response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) SetSuccessOp(v *Success) {
	if v == nil {
		x.xxx_hidden_Response = nil
		return
	}
	x.xxx_hidden_Response = &response_SuccessOp{v}
}

func (x *Response) SetError(v *Error) {
	if v == nil {
		x.xxx_hidden_Response = nil
		return
	}
	x.xxx_hidden_Response = &response_Error{v}
}

func (x *Response) HasResponse() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Response != nil
}

func (x *Response) HasSuccessOp() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Response.(*response_SuccessOp)
	return ok
}

func (x *Response) HasError() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Response.(*response_Error)
	return ok
}

func (x *Response) ClearResponse() {
	x.xxx_hidden_Response = nil
}

func (x *Response) ClearSuccessOp() {
	if _, ok := x.xxx_hidden_Response.(*response_SuccessOp); ok {
		x.xxx_hidden_Response = nil
	}
}

func (x *Response) ClearError() {
	if _, ok := x.xxx_hidden_Response.(*response_Error); ok {
		x.xxx_hidden_Response = nil
	}
}

const Response_Response_not_set_case case_Response_Response = 0
const Response_SuccessOp_case case_Response_Response = 1
const Response_Error_case case_Response_Response = 2

func (x *Response) WhichResponse() case_Response_Response {
	if x == nil {
		return Response_Response_not_set_case
	}
	switch x.xxx_hidden_Response.(type) {
	case *response_SuccessOp:
		return Response_SuccessOp_case
	case *response_Error:
		return Response_Error_case
	default:
		return Response_Response_not_set_case
	}
}

type Response_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Response:
	SuccessOp *Success
	Error     *Error
	// -- end of xxx_hidden_Response
}

func (b0 Response_builder) Build() *Response {
	m0 := &Response{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SuccessOp != nil {
		x.xxx_hidden_Response = &response_SuccessOp{b.SuccessOp}
	}
	if b.Error != nil {
		x.xxx_hidden_Response = &response_Error{b.Error}
	}
	return m0
}

type case_Response_Response protoreflect.FieldNumber

func (x case_Response_Response) String() string {
	md := file_qosm_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isResponse_Response interface {
	isResponse_Response()
}

type response_SuccessOp struct {
	SuccessOp *Success `protobuf:"bytes,1,opt,name=success_op,json=successOp,oneof"`
}

type response_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*response_SuccessOp) isResponse_Response() {}

func (*response_Error) isResponse_Response() {}

type AddHosts struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ips         *[]*IPPrefix           `protobuf:"bytes,1,rep,name=ips"`
	xxx_hidden_Priority    Priority               `protobuf:"varint,2,opt,name=priority,enum=qosm.v1.Priority"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddHosts) Reset() {
	*x = AddHosts{}
	mi := &file_qosm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHosts) ProtoMessage() {}

func (x *AddHosts) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddHosts) GetIps() []*IPPrefix {
	if x != nil {
		if x.xxx_hidden_Ips != nil {
			return *x.xxx_hidden_Ips
		}
	}
	return nil
}

func (x *AddHosts) GetPriority() Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Priority
		}
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *AddHosts) SetIps(v []*IPPrefix) {
	x.xxx_hidden_Ips = &v
}

func (x *AddHosts) SetPriority(v Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AddHosts) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddHosts) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Priority = Priority_PRIORITY_UNSPECIFIED
}

type AddHosts_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ips      []*IPPrefix
	Priority *Priority
}

func (b0 AddHosts_builder) Build() *AddHosts {
	m0 := &AddHosts{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ips = &b.Ips
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Priority = *b.Priority
	}
	return m0
}

type DeleteHosts struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ips         *[]*IPPrefix           `protobuf:"bytes,1,rep,name=ips"`
	xxx_hidden_Priority    Priority               `protobuf:"varint,2,opt,name=priority,enum=qosm.v1.Priority"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteHosts) Reset() {
	*x = DeleteHosts{}
	mi := &file_qosm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHosts) ProtoMessage() {}

func (x *DeleteHosts) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteHosts) GetIps() []*IPPrefix {
	if x != nil {
		if x.xxx_hidden_Ips != nil {
			return *x.xxx_hidden_Ips
		}
	}
	return nil
}

func (x *DeleteHosts) GetPriority() Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Priority
		}
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *DeleteHosts) SetIps(v []*IPPrefix) {
	x.xxx_hidden_Ips = &v
}

func (x *DeleteHosts) SetPriority(v Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteHosts) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteHosts) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Priority = Priority_PRIORITY_UNSPECIFIED
}

type DeleteHosts_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ips      []*IPPrefix
	Priority *Priority
}

func (b0 DeleteHosts_builder) Build() *DeleteHosts {
	m0 := &DeleteHosts{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ips = &b.Ips
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Priority = *b.Priority
	}
	return m0
}

type AddServices struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Services    *[]*Service            `protobuf:"bytes,1,rep,name=services"`
	xxx_hidden_Priority    Priority               `protobuf:"varint,2,opt,name=priority,enum=qosm.v1.Priority"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddServices) Reset() {
	*x = AddServices{}
	mi := &file_qosm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServices) ProtoMessage() {}

func (x *AddServices) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddServices) GetServices() []*Service {
	if x != nil {
		if x.xxx_hidden_Services != nil {
			return *x.xxx_hidden_Services
		}
	}
	return nil
}

func (x *AddServices) GetPriority() Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Priority
		}
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *AddServices) SetServices(v []*Service) {
	x.xxx_hidden_Services = &v
}

func (x *AddServices) SetPriority(v Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AddServices) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddServices) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Priority = Priority_PRIORITY_UNSPECIFIED
}

type AddServices_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Services []*Service
	Priority *Priority
}

func (b0 AddServices_builder) Build() *AddServices {
	m0 := &AddServices{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Services = &b.Services
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Priority = *b.Priority
	}
	return m0
}

type DeleteServices struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Services    *[]*Service            `protobuf:"bytes,1,rep,name=services"`
	xxx_hidden_Priority    Priority               `protobuf:"varint,2,opt,name=priority,enum=qosm.v1.Priority"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteServices) Reset() {
	*x = DeleteServices{}
	mi := &file_qosm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServices) ProtoMessage() {}

func (x *DeleteServices) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteServices) GetServices() []*Service {
	if x != nil {
		if x.xxx_hidden_Services != nil {
			return *x.xxx_hidden_Services
		}
	}
	return nil
}

func (x *DeleteServices) GetPriority() Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Priority
		}
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *DeleteServices) SetServices(v []*Service) {
	x.xxx_hidden_Services = &v
}

func (x *DeleteServices) SetPriority(v Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteServices) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteServices) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Priority = Priority_PRIORITY_UNSPECIFIED
}

type DeleteServices_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Services []*Service
	Priority *Priority
}

func (b0 DeleteServices_builder) Build() *DeleteServices {
	m0 := &DeleteServices{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Services = &b.Services
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Priority = *b.Priority
	}
	return m0
}

type EnableIfaces struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ifaces *[]*Interface          `protobuf:"bytes,1,rep,name=ifaces"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnableIfaces) Reset() {
	*x = EnableIfaces{}
	mi := &file_qosm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableIfaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableIfaces) ProtoMessage() {}

func (x *EnableIfaces) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnableIfaces) GetIfaces() []*Interface {
	if x != nil {
		if x.xxx_hidden_Ifaces != nil {
			return *x.xxx_hidden_Ifaces
		}
	}
	return nil
}

func (x *EnableIfaces) SetIfaces(v []*Interface) {
	x.xxx_hidden_Ifaces = &v
}

type EnableIfaces_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ifaces []*Interface
}

func (b0 EnableIfaces_builder) Build() *EnableIfaces {
	m0 := &EnableIfaces{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ifaces = &b.Ifaces
	return m0
}

type DisableIfaces struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ifaces *[]*Interface          `protobuf:"bytes,1,rep,name=ifaces"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DisableIfaces) Reset() {
	*x = DisableIfaces{}
	mi := &file_qosm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableIfaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableIfaces) ProtoMessage() {}

func (x *DisableIfaces) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DisableIfaces) GetIfaces() []*Interface {
	if x != nil {
		if x.xxx_hidden_Ifaces != nil {
			return *x.xxx_hidden_Ifaces
		}
	}
	return nil
}

func (x *DisableIfaces) SetIfaces(v []*Interface) {
	x.xxx_hidden_Ifaces = &v
}

type DisableIfaces_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ifaces []*Interface
}

func (b0 DisableIfaces_builder) Build() *DisableIfaces {
	m0 := &DisableIfaces{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ifaces = &b.Ifaces
	return m0
}

type FlushRules struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRules) Reset() {
	*x = FlushRules{}
	mi := &file_qosm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRules) ProtoMessage() {}

func (x *FlushRules) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FlushRules_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 FlushRules_builder) Build() *FlushRules {
	m0 := &FlushRules{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Error struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ErrorMessage *string                `protobuf:"bytes,1,opt,name=error_message,json=errorMessage"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_qosm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Error) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *Error) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Error) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Error) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ErrorMessage = nil
}

type Error_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ErrorMessage *string
}

func (b0 Error_builder) Build() *Error {
	m0 := &Error{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	return m0
}

type Success struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_qosm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_qosm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Success_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Success_builder) Build() *Success {
	m0 := &Success{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_qosm_proto protoreflect.FileDescriptor

const file_qosm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"qosm.proto\x12\aqosm.v1\"9\n" +
	"\aService\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\x05R\bprotocol\"M\n" +
	"\tInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aifindex\x18\x02 \x01(\x05R\aifindex\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\rR\x04rate\"9\n" +
	"\bIPPrefix\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x02 \x01(\x05R\tprefixLen\"\xb7\x03\n" +
	"\aRequest\x120\n" +
	"\tadd_hosts\x18\x01 \x01(\v2\x11.qosm.v1.AddHostsH\x00R\baddHosts\x129\n" +
	"\fdelete_hosts\x18\x02 \x01(\v2\x14.qosm.v1.DeleteHostsH\x00R\vdeleteHosts\x129\n" +
	"\fadd_services\x18\x03 \x01(\v2\x14.qosm.v1.AddServicesH\x00R\vaddServices\x12B\n" +
	"\x0fdelete_services\x18\x04 \x01(\v2\x17.qosm.v1.DeleteServicesH\x00R\x0edeleteServices\x12<\n" +
	"\renable_ifaces\x18\x05 \x01(\v2\x15.qosm.v1.EnableIfacesH\x00R\fenableIfaces\x12?\n" +
	"\x0edisable_ifaces\x18\x06 \x01(\v2\x16.qosm.v1.DisableIfacesH\x00R\rdisableIfaces\x126\n" +
	"\vflush_rules\x18\a \x01(\v2\x13.qosm.v1.FlushRulesH\x00R\n" +
	"flushRulesB\t\n" +
	"\acommand\"q\n" +
	"\bResponse\x121\n" +
	"\n" +
	"success_op\x18\x01 \x01(\v2\x10.qosm.v1.SuccessH\x00R\tsuccessOp\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x0e.qosm.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"^\n" +
	"\bAddHosts\x12#\n" +
	"\x03ips\x18\x01 \x03(\v2\x11.qosm.v1.IPPrefixR\x03ips\x12-\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x11.qosm.v1.PriorityR\bpriority\"a\n" +
	"\vDeleteHosts\x12#\n" +
	"\x03ips\x18\x01 \x03(\v2\x11.qosm.v1.IPPrefixR\x03ips\x12-\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x11.qosm.v1.PriorityR\bpriority\"j\n" +
	"\vAddServices\x12,\n" +
	"\bservices\x18\x01 \x03(\v2\x10.qosm.v1.ServiceR\bservices\x12-\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x11.qosm.v1.PriorityR\bpriority\"m\n" +
	"\x0eDeleteServices\x12,\n" +
	"\bservices\x18\x01 \x03(\v2\x10.qosm.v1.ServiceR\bservices\x12-\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x11.qosm.v1.PriorityR\bpriority\":\n" +
	"\fEnableIfaces\x12*\n" +
	"\x06ifaces\x18\x01 \x03(\v2\x12.qosm.v1.InterfaceR\x06ifaces\";\n" +
	"\rDisableIfaces\x12*\n" +
	"\x06ifaces\x18\x01 \x03(\v2\x12.qosm.v1.InterfaceR\x06ifaces\"\f\n" +
	"\n" +
	"FlushRules\",\n" +
	"\x05Error\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"\t\n" +
	"\aSuccess*I\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\n" +
	"\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x14B/Z-github.com/kakeetopius/qosm/internal/protobufb\beditionsp\xe9\a"

var file_qosm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qosm_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_qosm_proto_goTypes = []any{
	(Priority)(0),          // 0: qosm.v1.Priority
	(*Service)(nil),        // 1: qosm.v1.Service
	(*Interface)(nil),      // 2: qosm.v1.Interface
	(*IPPrefix)(nil),       // 3: qosm.v1.IPPrefix
	(*Request)(nil),        // 4: qosm.v1.Request
	(*Response)(nil),       // 5: qosm.v1.Response
	(*AddHosts)(nil),       // 6: qosm.v1.AddHosts
	(*DeleteHosts)(nil),    // 7: qosm.v1.DeleteHosts
	(*AddServices)(nil),    // 8: qosm.v1.AddServices
	(*DeleteServices)(nil), // 9: qosm.v1.DeleteServices
	(*EnableIfaces)(nil),   // 10: qosm.v1.EnableIfaces
	(*DisableIfaces)(nil),  // 11: qosm.v1.DisableIfaces
	(*FlushRules)(nil),     // 12: qosm.v1.FlushRules
	(*Error)(nil),          // 13: qosm.v1.Error
	(*Success)(nil),        // 14: qosm.v1.Success
}
var file_qosm_proto_depIdxs = []int32{
	6,  // 0: qosm.v1.Request.add_hosts:type_name -> qosm.v1.AddHosts
	7,  // 1: qosm.v1.Request.delete_hosts:type_name -> qosm.v1.DeleteHosts
	8,  // 2: qosm.v1.Request.add_services:type_name -> qosm.v1.AddServices
	9,  // 3: qosm.v1.Request.delete_services:type_name -> qosm.v1.DeleteServices
	10, // 4: qosm.v1.Request.enable_ifaces:type_name -> qosm.v1.EnableIfaces
	11, // 5: qosm.v1.Request.disable_ifaces:type_name -> qosm.v1.DisableIfaces
	12, // 6: qosm.v1.Request.flush_rules:type_name -> qosm.v1.FlushRules
	14, // 7: qosm.v1.Response.success_op:type_name -> qosm.v1.Success
	13, // 8: qosm.v1.Response.error:type_name -> qosm.v1.Error
	3,  // 9: qosm.v1.AddHosts.ips:type_name -> qosm.v1.IPPrefix
	0,  // 10: qosm.v1.AddHosts.priority:type_name -> qosm.v1.Priority
	3,  // 11: qosm.v1.DeleteHosts.ips:type_name -> qosm.v1.IPPrefix
	0,  // 12: qosm.v1.DeleteHosts.priority:type_name -> qosm.v1.Priority
	1,  // 13: qosm.v1.AddServices.services:type_name -> qosm.v1.Service
	0,  // 14: qosm.v1.AddServices.priority:type_name -> qosm.v1.Priority
	1,  // 15: qosm.v1.DeleteServices.services:type_name -> qosm.v1.Service
	0,  // 16: qosm.v1.DeleteServices.priority:type_name -> qosm.v1.Priority
	2,  // 17: qosm.v1.EnableIfaces.ifaces:type_name -> qosm.v1.Interface
	2,  // 18: qosm.v1.DisableIfaces.ifaces:type_name -> qosm.v1.Interface
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_qosm_proto_init() }
func file_qosm_proto_init() {
	if File_qosm_proto != nil {
		return
	}
	file_qosm_proto_msgTypes[3].OneofWrappers = []any{
		(*request_AddHosts)(nil),
		(*request_DeleteHosts)(nil),
		(*request_AddServices)(nil),
		(*request_DeleteServices)(nil),
		(*request_EnableIfaces)(nil),
		(*request_DisableIfaces)(nil),
		(*request_FlushRules)(nil),
	}
	file_qosm_proto_msgTypes[4].OneofWrappers = []any{
		(*response_SuccessOp)(nil),
		(*response_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qosm_proto_rawDesc), len(file_qosm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qosm_proto_goTypes,
		DependencyIndexes: file_qosm_proto_depIdxs,
		EnumInfos:         file_qosm_proto_enumTypes,
		MessageInfos:      file_qosm_proto_msgTypes,
	}.Build()
	File_qosm_proto = out.File
	file_qosm_proto_goTypes = nil
	file_qosm_proto_depIdxs = nil
}
